version: '3'

services:
  db:
    image: postgres
    expose:
        - "5432"
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
        - PORT=8000
    env_file:
        - .env
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    depends_on:
        - db
