version: '3'

services:
  db:
    image: postgres
    expose:
        - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    environment:
        - PORT=8000
    env_file:
        - .env
    ports:
        - "8000:8000"
    depends_on:
        - db
volumes:
  pgdata:
