# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('meaning', models.TextField()),
                ('extra', models.TextField(blank=True)),
                ('synonyms', models.CharField(blank=True, max_length=60)),
                ('related', models.CharField(blank=True, max_length=60)),
                ('origin', models.CharField(blank=True, max_length=60)),
                ('semantic_group', models.PositiveSmallIntegerField(default=1)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(max_length=60)),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('word', 'semantic_group', 'priority'),
            },
        ),
    ]
