# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='extra',
            new_name='extra_info',
        ),
        migrations.AddField(
            model_name='definition',
            name='phonetic',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='definition',
            name='private_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='reviewed',
            field=models.BooleanField(default=True),
        ),
    ]
