# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20161225_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='scientific',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='definition',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='definition',
            name='phonetic',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
