# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20161225_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='semantic_field',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
